# .github/workflows/git-sync.yml

on: push
jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "https://dharmik2319:${{ secrets.PAT }}@github.com/dharmik2319/cs-exhibition.git"
          source_branch: "main"
          destination_repo: "https://dharmik2319:${{ secrets.PAT }}@github.com/dharmik2319/dharmik2319.github.io.git"
          destination_branch: "main"
            #          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
            #          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
            #          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
